general.import = [
  "~/.config/alacritty/kanagawa-dragon.toml"
]

[env]
TERM = "xterm-256color"


[window]
decorations = "none"
opacity = 1
padding.x = 15
padding.y = 12
option_as_alt = "Both"

[font]
size = 18.0

[font.offset]
y = 2

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = false


[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
